name: Publish
on:
  push:
    branches:
      - '*.*.*'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm install
    - name: Run ESLint-Prod
      run: npm run lint -- --max-warnings=0
    - name: Compile TypeScript
      run: npm run compile
    - name: Minify JavaScript
      run: |
        for file in out/*.js; do
          npx uglifyjs "$file" -o "${file%.js}.js" --compress --mangle toplevel --mangle-props --comments "/\s(==\/?UserScript==|@.+$)/"
        done
    - name: Append .user.js to filename
      run: |
        for file in out/*.js; do
          mv "$file" .
        done
        for file in *.js; do
          mv "$file" "${file%.js}.user.js"
          sed -i "s/%DOWNLOAD%/https:\/\/github.com\/MSWS\/eGOMonkey\/releases\/latest\/download\/${file%.js}.user.js/g" "${file%.js}.user.js"
        done
    - name: Replace version globally
      run: |
        sed -i "s/%VERSION%/${{ env.VERSION }}/g" *.js
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.js"
        tag: ${{ env.VERSION }}
        makeLatest: true
        allowUpdates: true
        generateReleaseNotes: true

env:
  VERSION: ${{ github.ref_name }}-${{ github.run_id }}
