name: Publish
on:
  push:
    branches:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Append .user.js to filename
      run: |
        for file in src/*.js; do
          mv "$file" "src/${file%.js}.user.js"
        done
    - name: Replace version
      run: |
        sed -i "s/%VERSION%/${{ env.VERSION }}/g" src/*
    - name: Install modules
      run: npm install
    - name: Run ESLint-Prod
      run: npm run lint -- --max-warnings=0
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "src/*.js"
        tag: ${{ env.VERSION }}
        makeLatest: true
        allowUpdates: true

env:
  VERSION: ${{ github.ref_name }}.${{ github.run_number }}